[package]
name = "build-n-run"
version = "0.4.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.17"
structopt = "0.3.22"
ignore = "0.4.18"
strum = { version = "0.21.0", features = ["derive"] }
